#!/usr/bin/env node
// Generates data/version.js with the latest git commit hash for cache busting.
// Run before each deploy: node build.js

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

let hash;
try {
  hash = execSync("git rev-parse --short HEAD").toString().trim();
} catch {
  hash = Date.now().toString(36);
}

const out = `// Auto-generated by build.js — do not edit\nconst DATA_VERSION = "${hash}";\n`;
fs.writeFileSync(path.join(__dirname, "data", "version.js"), out);
console.log(`data/version.js → ${hash}`);
