#!/usr/bin/env node
// Generates data/version.js and updates cache-busting hashes in index.html.
// Run before each deploy: node build.js

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

let hash;
try {
  hash = execSync("git rev-parse --short HEAD").toString().trim();
} catch {
  hash = Date.now().toString(36);
}

// Update data/version.js
const out = `// Auto-generated by build.js — do not edit\nconst DATA_VERSION = "${hash}";\n`;
fs.writeFileSync(path.join(__dirname, "data", "version.js"), out);

// Update cache-busting in index.html
const htmlPath = path.join(__dirname, "index.html");
let html = fs.readFileSync(htmlPath, "utf-8");
html = html.replace(/css\/style\.css\?v=[^"]+/, `css/style.css?v=${hash}`);
html = html.replace(/js\/app\.js\?v=[^"]+/, `js/app.js?v=${hash}`);
fs.writeFileSync(htmlPath, html);

console.log(`data/version.js → ${hash}`);
console.log(`index.html → css/js cache busted with ${hash}`);
